import { useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import * as Tabs from '@radix-ui/react-tabs';
import { ApiError, post, queryClient, request, terminal, useApi } from './api';
import type { Attempt, Job, JobEvent, Page, SubmitResult } from './types';
import { Badge, Confirm, CopyButton, date, duration, ErrorNotice, Heading, JsonView, Panel, QueryState } from './ui';
import { AttemptTimeline } from './Timeline';
import s from './ui.module.css';
export function JobDetail() {
  const { id } = useParams(); const location = useLocation(); const navigate = useNavigate();
  const key = useRef(crypto.randomUUID());
  const [attemptCursor, setAttemptCursor] = useState(''); const [eventCursor, setEventCursor] = useState('');
  const detail = useQuery<Job, ApiError>({ queryKey: [`/jobs/${id}`], queryFn: ({signal}) => request(`/jobs/${id}`, {signal}), refetchInterval: q => q.state.data && terminal(q.state.data.state) ? false : 2000 });
  const interval = detail.data && terminal(detail.data.state) ? false : 2000;
  const attempts = useApi<Page<Attempt>>(`/jobs/${id}/attempts?limit=50${attemptCursor ? `&cursor=${attemptCursor}` : ''}`, interval);
  const events = useApi<Page<JobEvent>>(`/jobs/${id}/events?limit=50${eventCursor ? `&cursor=${eventCursor}` : ''}`, interval);
  const [notice, setNotice] = useState('');
  const mutation = useMutation({ mutationFn: async (action: 'cancel' | 'rerun') => { const result = await post<SubmitResult>(`/jobs/${id}/${action}`, {}, action === 'rerun' ? key.current : undefined); return { action, result }; }, onSuccess: ({action,result}) => { setNotice(action === 'cancel' ? 'Job canceled by the server.' : 'New linked job created.'); if (action === 'rerun') { key.current = crypto.randomUUID(); navigate(`/jobs/${result.job_id}`); } }, onSettled: () => { void queryClient.invalidateQueries(); } });
  const back = (location.state as {back?: string} | null)?.back ?? '/jobs';
  return <><Link to={back} className={s.back}>← Back to jobs</Link><Heading title="Job inspection" eyebrow="EXECUTION / TRACE"/>{mutation.error && <ErrorNotice error={mutation.error}/>}<p role="status">{notice}</p><QueryState query={detail}>{job => <>
    <section className={s.jobHeader}><div className={s.toolbar}><Badge state={job.state}/><span className={s.muted}>{job.handler} · v{job.handler_version}</span><div className={s.actions}><Confirm label="Cancel" title="Cancel pending job?" disabled={detail.isError || mutation.isPending || !['queued','retry_wait'].includes(job.state)} pending={mutation.isPending} onConfirm={() => mutation.mutateAsync('cancel').then(() => undefined)}>Only pending work can be canceled. If a worker claims this job first, the server will reject cancellation.</Confirm><Confirm label="Rerun" title="Create a new linked job?" disabled={detail.isError || mutation.isPending || !terminal(job.state)} pending={mutation.isPending} onConfirm={() => mutation.mutateAsync('rerun').then(() => undefined)}>A rerun creates a new job with the same input. At-least-once execution can repeat side effects. The original history is preserved.</Confirm></div></div><h2 className={s.jobId}>{job.id}</h2><CopyButton text={job.id} label="Copy job ID"/><dl className={s.facts}><div><dt>Queue</dt><dd><Link to={`/queues/${encodeURIComponent(job.queue)}`}>{job.queue}</Link></dd></div><div><dt>Submitted · UTC</dt><dd>{date(job.created_at)}</dd></div><div><dt>Attempt budget</dt><dd>{job.attempt_count} / {job.max_attempts}</dd></div><div><dt>Runtime limit</dt><dd>{duration(job.timeout_ms)}</dd></div><div><dt>Available / retry at</dt><dd>{date(job.available_at)}</dd></div><div><dt>Lease expires</dt><dd>{date(job.lease_expires_at)}</dd></div></dl>{job.last_error_summary && <p className={s.failure}>{job.last_error_code}: {job.last_error_summary}</p>}{job.state === 'queued' && <p className={s.muted}>Waiting for availability and a compatible worker. Paused queues do not accept new claims.</p>}{job.rerun_of && <p>Rerun of <Link to={`/jobs/${job.rerun_of}`}>{job.rerun_of}</Link></p>}</section>
    <Tabs.Root defaultValue="attempts" className={s.tabs}><Tabs.List aria-label="Job details">{['attempts','input','output','events'].map(tab => <Tabs.Trigger key={tab} value={tab}>{tab[0].toUpperCase()+tab.slice(1)}</Tabs.Trigger>)}</Tabs.List><Tabs.Content value="attempts"><Panel title="Attempt timeline"><QueryState query={attempts}>{data => <><AttemptTimeline attempts={data.items}/><div className={s.pagination}><button disabled={!attemptCursor} onClick={() => setAttemptCursor('')}>First attempts</button><button disabled={!data.next_cursor} onClick={() => setAttemptCursor(String(data.next_cursor))}>More attempts</button></div></>}</QueryState>{job.state === 'retry_wait' && <p className={s.stale}>↻ Retry scheduled for {date(job.available_at)}. Remaining budget: {job.max_attempts-job.attempt_count}.</p>}</Panel></Tabs.Content><Tabs.Content value="input"><Panel title="Validated input"><JsonView value={job.payload}/></Panel></Tabs.Content><Tabs.Content value="output"><Panel title="Result">{job.result === null ? <p>No committed output yet.</p> : <JsonView value={job.result}/>}</Panel></Tabs.Content><Tabs.Content value="events"><Panel title="Durable lifecycle events"><QueryState query={events}>{data => <>{data.items.map(e => <details key={e.seq}><summary>#{e.seq} {e.kind} · {date(e.created_at)}</summary><JsonView value={e.detail}/></details>)}{!data.items.length && <p>No retained events.</p>}<div className={s.pagination}><button disabled={!eventCursor} onClick={() => setEventCursor('')}>First events</button><button disabled={!data.next_cursor} onClick={() => setEventCursor(String(data.next_cursor))}>More events</button></div></>}</QueryState></Panel></Tabs.Content></Tabs.Root></>}</QueryState></>;
}
