import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useApi } from './api';
import type { Handler, Job, Overview, Page, Queue } from './types';
import { Badge, date, duration, Heading, QueryState } from './ui';
import s from './ui.module.css';
export function Jobs() {
  const [params, setParams] = useSearchParams(); const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const apiParams = new URLSearchParams(params); apiParams.delete('history');
  const jobs = useApi<Page<Job>>(`/jobs?${apiParams}`, 2000);
  const overview = useApi<Overview>('/overview');
  const queues = useApi<{items: Queue[]}>('/queues');
  const handlers = useApi<{items: Handler[]}>('/handlers', false);
  function filter(key: string, value: string) { const next = new URLSearchParams(params); next.delete('cursor'); next.delete('history'); if (value) next.set(key, value); else next.delete(key); setParams(next); }
  function page(nextCursor?: string | null) {
    const next = new URLSearchParams(params); const history = (params.get('history') ?? '').split(',').filter(Boolean);
    if (nextCursor) { history.push(params.get('cursor') ?? '_'); next.set('cursor', nextCursor); } else { const previous = history.pop(); if (previous && previous !== '_') next.set('cursor', previous); else next.delete('cursor'); }
    if (history.length) next.set('history', history.join(',')); else next.delete('history'); setParams(next);
  }
  return <><Heading title="Jobs" eyebrow="EXECUTION REGISTER"><span className={s.muted}>Durable work. Inspectable history.</span></Heading><QueryState query={overview}>{data => <><div className={s.metrics}>{(['queued','running','retry_wait','failed'] as const).map(state => <div key={state}><span>{state.replace('_', ' ')}</span><strong>{data.jobs[state] ?? 0}</strong></div>)}<div><span>Oldest due</span><strong>{duration(data.queues.reduce<number | null>((max, q) => q.oldest_due_age_ms == null ? max : Math.max(max ?? 0, q.oldest_due_age_ms), null))}</strong></div></div><p className={s.muted}>Counts cover all retained jobs, not a rolling rate. Snapshot {date(data.as_of)}.</p></>}</QueryState>
    <form className={s.filters} onSubmit={e => { e.preventDefault(); if (search.trim()) navigate(`/jobs/${encodeURIComponent(search.trim())}`, {state: {back: `/jobs?${params}`}}); }}><label className={s.grow}>Find exact job ID<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Full job ID"/></label><button>Inspect</button><label>Queue<select value={params.get('queue') ?? ''} onChange={e => filter('queue',e.target.value)}><option key="all-q" value="">All queues</option>{queues.data?.items.map(q => <option key={q.name}>{q.name}</option>)}</select></label><label>State<select value={params.get('state') ?? ''} onChange={e => filter('state',e.target.value)}><option key="all-s" value="">All states</option>{['queued','running','retry_wait','succeeded','failed','canceled'].map(v => <option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label><label>Handler<select value={params.get('handler') ?? ''} onChange={e => filter('handler',e.target.value)}><option key="all-h" value="">All handlers</option>{handlers.data?.items.map(h => <option key={h.name}>{h.name}</option>)}</select></label><label>Created after (UTC)<input type="datetime-local" value={(params.get('created_after') ?? '').slice(0,16)} onChange={e => filter('created_after',e.target.value ? `${e.target.value}:00Z` : '')}/></label><button type="button" onClick={() => { setSearch(''); setParams({}); }}>Reset filters</button></form>
    <QueryState query={jobs}>{data => <><div className={s.tableWrap} tabIndex={0} aria-label="Jobs table scroll region"><table><caption className={s.srOnly}>Jobs ordered by creation time</caption><thead><tr><th scope="col">Status</th><th scope="col">Handler / Job ID</th><th scope="col">Queue</th><th scope="col">Attempts</th><th scope="col" aria-sort="descending">Created ↓</th><th scope="col">Duration</th></tr></thead><tbody>{data.items.map(job => <tr key={job.id}><td><Badge state={job.state}/></td><td><Link to={`/jobs/${job.id}`} state={{ back: `/jobs?${params}` }}>{job.handler}</Link><span className={s.id}>{job.id}</span></td><td><Link to={`/queues/${encodeURIComponent(job.queue)}`}>{job.queue}</Link></td><td className={s.mono}>{job.attempt_count} / {job.max_attempts}</td><td className={s.mono}>{date(job.created_at)}</td><td className={s.mono}>{duration(job.started_at && job.finished_at ? Date.parse(job.finished_at)-Date.parse(job.started_at) : null)}</td></tr>)}</tbody></table></div>{!data.items.length && <div className={s.empty}><h2>{params.size ? 'No jobs match these filters' : 'Your execution register is empty'}</h2><p>{params.size ? 'Try another queue or reset the filters.' : 'Start a worker with relay worker start, then submit a built-in job to inspect its execution.'}</p><Link to="/jobs/new">Submit your first job →</Link></div>}<div className={s.pagination}><label>Per page <select value={params.get('limit') ?? '50'} onChange={e => filter('limit',e.target.value)}>{[25,50,100].map(n => <option key={String(n)}>{n}</option>)}</select></label><span>{data.items.length} jobs shown · live traversal, not a frozen snapshot</span><button disabled={!params.has('cursor')} onClick={() => page()}>Previous</button><button disabled={!data.next_cursor} onClick={() => page(data.next_cursor)}>Next</button></div></>}</QueryState></>;
}
