import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { post, queryClient, useApi } from './api';
import type { Page, Queue, SystemInfo, Worker } from './types';
import { Badge, Confirm, date, duration, ErrorNotice, Heading, JsonView, Panel, QueryState } from './ui';
import s from './ui.module.css';
export function Queues() {
  const {name} = useParams(); const queues = useApi<{items: Queue[]}>('/queues'); const [notice,setNotice] = useState('');
  const mutation = useMutation({mutationFn: ({name,paused}: {name:string;paused:boolean}) => post(`/queues/${encodeURIComponent(name)}/${paused ? 'resume' : 'pause'}`), onSuccess: () => setNotice('Queue state updated by the server.'), onSettled: () => { void queryClient.invalidateQueries(); }});
  return <><Heading title={name ? `Queue / ${name}` : 'Queues'} eyebrow="CLAIM CONTROL"/><p className={s.muted}>Pause new claims without interrupting in-flight attempts.</p>{name && <Link to="/queues">← All queues</Link>}<p role="status">{notice}</p>{mutation.error && <ErrorNotice error={mutation.error}/>}<QueryState query={queues}>{data => <>{name && !data.items.some(q => q.name === name) && <Panel title="Queue not found"><p>This queue is not registered.</p></Panel>}<div className={s.cards}>{data.items.filter(q => !name || q.name === name).map(q => <Panel key={q.name}><div className={s.toolbar}><h2><Link to={`/queues/${encodeURIComponent(q.name)}`}>{q.name}</Link></h2><Badge state={q.paused ? 'paused' : 'active'}/></div><dl className={s.facts}><div><dt>Due depth</dt><dd>{q.due_depth}</dd></div><div><dt>Oldest due</dt><dd>{duration(q.oldest_due_age_ms)}</dd></div><div><dt>Created</dt><dd>{date(q.created_at)}</dd></div></dl><div className={s.actions}><Link to={`/jobs?queue=${encodeURIComponent(q.name)}`}>Inspect jobs →</Link><Confirm label={q.paused ? 'Resume' : 'Pause'} title={`${q.paused ? 'Resume' : 'Pause'} queue ${q.name}?`} disabled={queues.isError || mutation.isPending} pending={mutation.isPending} onConfirm={() => mutation.mutateAsync(q).then(() => undefined)}>{q.paused ? 'Due jobs become eligible for compatible workers to claim.' : 'New claims stop. Already running attempts continue and may complete or retry.'}</Confirm></div></Panel>)}</div>{!data.items.length && <p>No registered queues.</p>}</>}</QueryState></>;
}
export function Workers() {
  const {id} = useParams(); const [cursor,setCursor] = useState('');
  const workers = useApi<Page<Worker>>(`/workers?limit=100${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`);
  return <><Heading title={id ? 'Worker inspection' : 'Workers'} eyebrow="EXECUTION CAPACITY"/><p className={s.muted}>A fresh heartbeat does not prove every handler is healthy. Stale or draining workers may not claim new jobs.</p>{id && <Link to="/workers">← All workers</Link>}<QueryState query={workers}>{data => <>{id && !data.items.some(w => w.id === id) && <Panel title="Worker not on this page"><p>Continue through worker pages to find this boot ID.</p></Panel>}<div className={s.cards}>{data.items.filter(w => !id || w.id === id).map(w => <Panel key={w.id}><div className={s.toolbar}><h2>{w.hostname}</h2><Badge state={w.availability}/></div><Link className={s.id} to={`/workers/${w.id}`}>{w.id}</Link><dl className={s.facts}><div><dt>State</dt><dd>{w.state}</dd></div><div><dt>Heartbeat age</dt><dd>{duration(w.heartbeat_age_ms)}</dd></div><div><dt>Capacity</dt><dd>{w.active_attempts} active / {w.concurrency} slots</dd></div><div><dt>Available slots</dt><dd>{w.available_slots}</dd></div><div><dt>Process ID</dt><dd>{w.process_id}</dd></div><div><dt>Booted · UTC</dt><dd>{date(w.started_at)}</dd></div></dl><p>Queues: {w.queues.map(q => <Link key={q} className={s.queueLink} to={`/queues/${encodeURIComponent(q)}`}>{q}</Link>)}</p><details open={Boolean(id)}><summary>Handler versions and heartbeat</summary><p>{date(w.heartbeat_at)}</p><JsonView value={w.handler_versions}/></details></Panel>)}</div>{!data.items.length && <Panel title="No worker registered"><p>Start a supervisor with <code>relay worker start</code>. Queued work remains durable.</p></Panel>}<div className={s.pagination}><button disabled={!cursor} onClick={() => setCursor('')}>First workers</button><button disabled={!data.next_cursor} onClick={() => setCursor(String(data.next_cursor))}>More workers</button></div></>}</QueryState></>;
}
export function System() {
  const system = useApi<SystemInfo>('/system'); const ready = useApi<{status:string;database:boolean;maintenance:boolean}>('/health/ready'); const live = useApi<{status:string}>('/health/live');
  return <><Heading title="System" eyebrow="INSTALLATION DIAGNOSTICS"/><div className={s.cards}><Panel title="Installation"><QueryState query={system}>{data => <><dl className={s.facts}><div><dt>Version</dt><dd>{data.version}</dd></div><div><dt>Schema</dt><dd>{data.schema_version}</dd></div><div><dt>Database + WAL</dt><dd>{data.database_size_bytes.toLocaleString()} bytes</dd></div><div><dt>Last maintenance</dt><dd>{date(data.maintenance_last_at)}</dd></div></dl><details><summary>Copy safe diagnostics</summary><JsonView value={data}/></details></>}</QueryState></Panel><Panel title="Readiness"><QueryState query={ready}>{data => <><Badge state={data.status}/><p>Database accessible: {data.database ? 'yes' : 'no'}</p><p>Maintenance fresh: {data.maintenance ? 'yes' : 'no'}</p></>}</QueryState><QueryState query={live}>{data => <p>API process liveness: {data.status}</p>}</QueryState></Panel><Panel title="Local trust boundary"><p>One installation, one host. Trusted, registered handlers; not an untrusted-code sandbox.</p><p>Tokens live in memory only. Disconnect clears the token and cached data.</p><p>Backup and retention remain local: <code>relay db backup --help</code> / <code>relay db prune --help</code>.</p></Panel></div></>;
}
